### PR TITLE
Needs sudo permision to build docker images

### PR DESCRIPTION
**Pull request by ibex107**
Without sudo the terminal returns permission denied error.

### CODE REVIEW

**Comment by fireFerry** [comment]
You should add yourself to the docker group instead of running it as root.

**Comment by ibex107** [comment]
I appologize for bringing up such a dumb change. I didn't know about it. But shouldn't in the script be the command to add the user in the docker group? From what I know the installation of docker doesn't add the user to the group. Kind regards.

**Comment by fireFerry** [comment]
well if you install docker yourself, you have the choice to run startup.sh with sudo, or add the current user to the docker group to use Docker

**Comment by ibex107** [comment]
We don't understand each other. Of course you can add yourself to the docker group after install but I tought the docker install script didn't have the command to add the user to the group. In the end it was just my fault on ym side. I appologize once again for causing this much trubble.
Kind regards and I wish the best for byob.

**Pull request closed without merging**
