### PR TITLE
Miner Program

### PR DESCRIPTION
**Pull request by SinSinati5**
If you guys like the idea I can add support for other gpu's and operating systems.

### CODE REVIEW

**Review by Lillythefox — CHANGES_REQUESTED** [review]
Looks incomplete.
Are you getting an external dependency?

**Comment by SinSinati5** [comment]
> Looks incomplete. Are you getting an external dependency?

No, that whole thing is enough for mining on a windows nvidia.

**Comment by SinSinati5** [comment]
> Looks incomplete.
> 
> Are you getting an external dependency? 

But I updated it

**Comment by Stetsed** [comment]
Some issues I noted which should probally be fixed:

1. For the linux downloads for the miner modules they are coming from mediafire. This should probally be placed with downloading directly from source instead. As this is currently only done with windows.

Some improvements that could be made:
1. Maybe add distro detection for the linux sub-module as some distro's, like arch-linux have a package for t-rex which could be used instead.
2. Maybe add location detection for the pool selection, I currently see the ru version of Hiveon being used but they have more servers so you could determine a roughe location via IP and then select a pool via that.

**Comment by SinSinati5** [comment]
> Some issues I noted which should probally be fixed:
> 
> 
> 
> 1. For the linux downloads for the miner modules they are coming from mediafire. This should probally be placed with downloading directly from source instead. As this is currently only done with windows.
> 
> 
> 
> Some improvements that could be made:
> 
> 1. Maybe add distro detection for the linux sub-module as some distro's, like arch-linux have a package for t-rex which could be used instead.
> 
> 2. Maybe add location detection for the pool selection, I currently see the ru version of Hiveon being used but they have more servers so you could determine a roughe location via IP and then select a pool via that.

For the issue I fixed it.

For the first improvement, do you mean arch has t-rex built in?

For the pool, different cryptos have different pools and also people prefer and use different pools so I can't select that for them because its something based on the user.

Hoped that helped, Thankyou for the feedback

**Comment by Stetsed** [comment]
> > Some issues I noted which should probally be fixed:
> > 
> > 1. For the linux downloads for the miner modules they are coming from mediafire. This should probally be placed with downloading directly from source instead. As this is currently only done with windows.
> > 
> > Some improvements that could be made:
> > 
> > 1. Maybe add distro detection for the linux sub-module as some distro's, like arch-linux have a package for t-rex which could be used instead.
> > 2. Maybe add location detection for the pool selection, I currently see the ru version of Hiveon being used but they have more servers so you could determine a roughe location via IP and then select a pool via that.
> 
> For the issue I fixed it.
> 
> For the first improvement, do you mean arch has t-rex built in?
> 
> For the pool, different cryptos have different pools and also people prefer and use different pools so I can't select that for them because its something based on the user.
> 
> Hoped that helped, Thankyou for the feedback

Ah, I see that you have made server an option which is good. I said you should add detection because I thought you where only gonna build Hiveon in but you changed it so good.

What I ment with point 1 was that arch and others have the package in there repo's but honestly downloading it like you have done is better so it's fine.

Looks like a good change to the project :D, haven't tested myself but will keep track of it as it looks nice.

**Comment by malwaredllc** [comment]
Interesting, I will test this out locally

**Comment by SinSinati5** [comment]
Can you tell me how you take input from the web gui?  thats the final step to this.

**Comment by malwaredllc** [comment]
@SinSinati5 sorry github actions closed this, I have reopened it.

If I understand your question correctly, the user input for the miner module is entered in the UI [here](https://github.com/malwaredllc/byob/blob/master/web-gui/buildyourownbotnet/templates/sessions.html#L73-L91) (if you Cntrl+F for "mine" in that file you'll find the various things that interact with it).

Let me know if that answers your question.

**Comment by SinSinati5** [comment]
Hey malwaredllc,

I got the vars in place but I can't get the hang of how the thing communicates with the module.  If u could get me straight on that it would be appreciated.

**Comment by SinSinati5** [comment]
@malwaredllc I wanna get back on this project but don't know how the modules interact with the html server that is ran on the attacking computer. How would the module get the instructions from the attacking machine?

**Pull request closed without merging**
