### PR TITLE
Adds Tab Completion

### PR DESCRIPTION
**Pull request by thehappydinoa**
This implements [`readline`](https://docs.python.org/2/library/readline.html) into `server.py` allowing users to use tab completion and arrow keys to return to previous command just as normal terminal. Hope this helped. :smile:

### CODE REVIEW

**Comment by thehappydinoa** [comment]
I see that Travis had a hard time with `rlcompleter`. I believe that I did it correctly as it is used as [such](https://docs.python.org/2/library/rlcompleter.html): 
```python
try:
    import readline
except ImportError:
    print "Module readline not available."
else:
    import rlcompleter
    readline.parse_and_bind("tab: complete")
```

**Comment by malwaredllc** [comment]
Adding tab completion would be an awesome improvement. I think I may modify the Travis CI build configuration to allow for unused imports so that this can be implemented without build errors.

**Comment by thehappydinoa** [comment]
@malwaredllc that would be great.

**Comment by malwaredllc** [comment]
I updated the Travis CI config to allow for unused imports but this build still errors, but your fork is still using the old config so I think you may need to do a pull first.

**Comment by thehappydinoa** [comment]
All fixed?

**Comment by malwaredllc** [comment]
Looks good, merging now.

**Pull request merged**
