### PR TITLE
fix: broken pip and pyinstaller and update docker files

### PR DESCRIPTION
**Pull request by alhazmy13**

### CODE REVIEW

**Comment by malwaredllc** [comment]
Have you tested the changes thoroughly? What specific bugs are these changes attempting to fix?

**Comment by martinboca** [comment]
> Have you tested the changes thoroughly? What specific bugs are these changes attempting to fix?

Before I use this fix, when I run "sudo ./startup.sh" it got stuck at PyInstaller3.6...
I was using the instructions on your video (@malwaredllc) and tried on Kali Linux and Ubuntu with no success.

After this fix I was able to get everything installed and running. Only one thing... It's normal when I try to make a windows payload only shows x32 option and no x64?

Thanks @alhazmy13 for doing this fix!

**Comment by martinboca** [comment]
**UPDATE**:
I could remove the ModuleNotFoundError by updating numpy to last version (and removing for requirements.txt).
**After doing this the python payload works**! But the executable on linux has the same errors.

When I try to take a screenshot Web says that the screenshot was saved to "Exfiltrated Files" but there's nothing there, and server output this:
```
[2020-11-10 20:02:35,709] ERROR in app: Exception on /api/file/add [POST]
Traceback (most recent call last):
  File "/home/martin/Desktop/byob-master/web-gui/buildyourownbotnet/api/files/routes.py", line 25, in file_add
    data = base64.b64decode(b64_data)
  File "/usr/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
**binascii.Error: Invalid base64-encoded string: number of data characters (29) cannot be 1 more than a multiple of 4**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/martin/Desktop/byob-master/web-gui/buildyourownbotnet/api/files/routes.py", line 30, in file_add
    print('/api/file/add error: invalid data ' + str(data))
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by alhazmy13** [comment]
> Have you tested the changes thoroughly? What specific bugs are these changes attempting to fix?

Yes, it's fixed https://github.com/malwaredllc/byob/issues/315 , https://github.com/malwaredllc/byob/issues/243, https://github.com/pyinstaller/pyinstaller/issues/4845 and https://github.com/cdrx/docker-pyinstaller/issues/103

**Comment by admiralyt** [comment]
bro i got an error while installing the byob 

Error - 
 File "run.py", line 1, in <module>
    from buildyourownbotnet import app
  File "/home/blackbox/new/byob/web-gui/buildyourownbotnet/__init__.py", line 18, in <module>
    db = SQLAlchemy(app)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 716, in __init__
    self.Model = self.make_declarative_base(model_class, metadata)
  File "/usr/lib/python3/dist-packages/flask_sqlalchemy/__init__.py", line 798, in make_declarative_base
    model.query_class = self.Query
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/api.py", line 79, in __setattr__
    _add_attribute(cls, key, value)
  File "/usr/lib/python3/dist-packages/sqlalchemy/ext/declarative/base.py", line 802, in _add_attribute
    type.__setattr__(cls, key, value)
TypeError: can't apply this __setattr__ to DefaultMeta object

**Comment by Csicso64a** [comment]
What can i do ? -_-

`Step 18/25 : RUN /usr/bin/pip install pyinstaller==$PYINSTALLER_VERSION
 ---> Running in 3b1f81404379
0050:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
009c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142                                                                                                           
Collecting pyinstaller==3.6                                                                                             
  Downloading PyInstaller-3.6.tar.gz (3.5 MB)
  Installing build dependencies: started`

**Comment by malwaredllc** [comment]
Merging based on recommendations of support team who have tested this successfully.

**Pull request merged**
